// Generated by Xata Codegen 0.29.4. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "article",
    columns: [
      {
        name: "ID",
        type: "varchar(128)",
        notNull: true,
        unique: true,
        defaultValue: null,
      },
      {
        name: "content",
        type: "text",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
      {
        name: "headerText",
        type: "varchar(191)",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
    ],
  },
  {
    name: "article_category",
    columns: [
      {
        name: "ID",
        type: "varchar(128)",
        notNull: true,
        unique: true,
        defaultValue: null,
      },
      {
        name: "name",
        type: "varchar(50)",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
    ],
  },
  {
    name: "article_to_article_category",
    columns: [
      {
        name: "articleId",
        type: "varchar(128)",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
      {
        name: "categoryId",
        type: "varchar(128)",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
    ],
  },
  {
    name: "blocked_user",
    columns: [
      {
        name: "ID",
        type: "varchar(128)",
        notNull: true,
        unique: true,
        defaultValue: null,
      },
      {
        name: "blocked_ID",
        type: "varchar(128)",
        notNull: false,
        unique: false,
        defaultValue: null,
      },
      {
        name: "blocked_by_ID",
        type: "varchar(128)",
        notNull: false,
        unique: false,
        defaultValue: null,
      },
    ],
  },
  {
    name: "update_note",
    columns: [
      {
        name: "ID_&_Version",
        type: "character(4)",
        notNull: true,
        unique: true,
        defaultValue: null,
      },
      {
        name: "created_at",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
      {
        name: "text",
        type: "text",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
      {
        name: "updated_at",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
      },
    ],
  },
  {
    name: "user",
    columns: [
      {
        name: "created_at",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
      },
      {
        name: "discord_id",
        type: "varchar",
        notNull: false,
        unique: true,
        defaultValue: null,
      },
      {
        name: "github_id",
        type: "int",
        notNull: false,
        unique: true,
        defaultValue: null,
      },
      {
        name: "google_id",
        type: "varchar",
        notNull: false,
        unique: true,
        defaultValue: null,
      },
      {
        name: "id",
        type: "text",
        notNull: true,
        unique: true,
        defaultValue: null,
      },
      {
        name: "profile_picture",
        type: "varchar(255)",
        notNull: false,
        unique: false,
        defaultValue: null,
      },
      {
        name: "updated_at",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
      },
      {
        name: "username",
        type: "varchar(65)",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
      {
        name: "username_ID",
        type: "character(4)",
        notNull: true,
        unique: true,
        defaultValue: null,
      },
      {
        name: "username_with_username_ID",
        type: "varchar(70)",
        notNull: true,
        unique: true,
        defaultValue: null,
      },
    ],
  },
  {
    name: "user_friendship",
    columns: [
      {
        name: "ID",
        type: "varchar(128)",
        notNull: true,
        unique: true,
        defaultValue: null,
      },
      {
        name: "created_at",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
      },
      {
        name: "friend_ID",
        type: "varchar(128)",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
      {
        name: "friend_username_with_username_ID",
        type: "varchar(70)",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
      {
        name: "updated_at",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: "now()",
      },
      {
        name: "user_ID",
        type: "varchar(128)",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
    ],
  },
  {
    name: "user_session",
    columns: [
      {
        name: "expires_at",
        type: "datetime",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
      {
        name: "id",
        type: "varchar(128)",
        notNull: true,
        unique: true,
        defaultValue: null,
      },
      {
        name: "user_id",
        type: "text",
        notNull: true,
        unique: false,
        defaultValue: null,
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Article = InferredTypes["article"];
export type ArticleRecord = Article & XataRecord;

export type ArticleCategory = InferredTypes["article_category"];
export type ArticleCategoryRecord = ArticleCategory & XataRecord;

export type ArticleToArticleCategory =
  InferredTypes["article_to_article_category"];
export type ArticleToArticleCategoryRecord = ArticleToArticleCategory &
  XataRecord;

export type BlockedUser = InferredTypes["blocked_user"];
export type BlockedUserRecord = BlockedUser & XataRecord;

export type UpdateNote = InferredTypes["update_note"];
export type UpdateNoteRecord = UpdateNote & XataRecord;

export type User = InferredTypes["user"];
export type UserRecord = User & XataRecord;

export type UserFriendship = InferredTypes["user_friendship"];
export type UserFriendshipRecord = UserFriendship & XataRecord;

export type UserSession = InferredTypes["user_session"];
export type UserSessionRecord = UserSession & XataRecord;

export type DatabaseSchema = {
  article: ArticleRecord;
  article_category: ArticleCategoryRecord;
  article_to_article_category: ArticleToArticleCategoryRecord;
  blocked_user: BlockedUserRecord;
  update_note: UpdateNoteRecord;
  user: UserRecord;
  user_friendship: UserFriendshipRecord;
  user_session: UserSessionRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://404-s-workspace-68cmk0.eu-central-1.xata.sh/db/main-database",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
